#服务端口
server:
  port: 8501
#服务名称
spring:
  application:
    name: tdp-hk-8700-server
  redis:
    #数据库索引
    database: 10
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        #最大连接数
        max-active: 8
        #最大阻塞等待时间(负数表示没限制)
        max-wait: -1
        #最大空闲
        max-idle: 8
        #最小空闲
        min-idle: 0
    #连接超时时间
    timeout: 10000
#tdp配置
tdp:
  #第三方接口配置参数
  params:
    host: http://192.168.10.21
    appKey: fac30958
    secret: 40b4809c4f204f80a9d81a288e5a4d8c
  #监控
  #定时任务
  schedule:
    sync-camera: 0 0 0 0/1 * ?
    save-to-redis: 0 0/1 * * * ?
    #停车场
    sync-car-park-device: 0 0/1 * * * ?
    sync-car-park-record: 0 0/1 * * * ?
    #监控客流
    sync-passenger-flow-record: 0 0/1 * * * ?
  first-sync-time:
    car-park-record: 2018-08-01 00:00:00
    passenger-flow-record: 2019-02-19 00:00:00
#log
logging:
  config: classpath:log4j2.xml

##服务注册到eureka地址
#eureka连接信息
eureka:
  instance:
    hostname: 127.0.0.1
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8100/eureka/


