#服务名称
spring:
  application:
    name: tdp-hk-8700-server
  redis:
    #数据库索引
    database: 10
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        #最大连接数
        max-active: 8
        #最大阻塞等待时间(负数表示没限制)
        max-wait: -1
        #最大空闲
        max-idle: 8
        #最小空闲
        min-idle: 0
    #连接超时时间
    timeout: 10000
#服务端口
server:
  port: 8501
#tdp配置
tdp:
  hk8700:
    #第三方接口配置参数
    params:
      host: http://172.10.52.2/cms/services/ICommonService?wsdl
      appKey:
      secret:
    #监控
    camera:
      #定时任务
      schedule:
        sync-camera: 0 0 0 0/1 * ?
        save-to-redis: 0 0/1 * * * ?
    #停车场
    car-park:
      schedule:
        sync-car-park-device: 0 0/1 * * * ?
        sync-car-park-record: 0 0/1 * * * ?
      first-sync-time:
        car-park-record: 2019-01-01 00:00:00
#log
logging:
  config: classpath:log4j2.xml



