#服务端口
server:
  port: 8501
#服务名称
spring:
  application:
    name: tdp-hk-8700-server
  redis:
    #数据库索引
    database: 10
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        #最大连接数
        max-active: 8
        #最大阻塞等待时间(负数表示没限制)
        max-wait: -1
        #最大空闲
        max-idle: 8
        #最小空闲
        min-idle: 0
    #连接超时时间
    timeout: 10000
  #activemq配置
  activemq:
    broker-url: failover:tcp://192.168.10.21:61618
    in-memory: false
    packages:
      trust-all: false
    pool:
      enabled: false
      expiry-timeout: 0
      idle-timeout: 30000
      max-connections: 1
      #当有"JMSException"时尝试重新连接
      reconnect-on-exception: true
  jms:
    pub-sub-domain: true
#tdp配置
tdp:
  hk:
    #电脑高清信号,车载设备,人员定位设备,SOS设备
    invalid-group: 0ae4a873134b46728b05a4bc5a3e0ff6,df75123868d2440b9976a16af886b80e,30d968d4011e4821aca51c931bbb79fe,9dcccf13c5324051ad24d51133124856
    #active destination
    #gps
    gps-destination: openapi.event.topic
    #客流
    common-destination: openapi.vss.topic
  #第三方接口配置参数
  params:
    host: http://192.168.10.21
    appKey: fac30958
    secret: 40b4809c4f204f80a9d81a288e5a4d8c
  #监控
  #定时任务
  schedule:
    sync-camera: 0 0 0 0/1 * ?
    save-to-redis: 0 0/1 * * * ?
    #停车场
    sync-car-park-device: 0 0/1 * * * ?
    sync-car-park-record: 0 0/1 * * * ?
    #监控客流
    sync-passenger-flow-record: 0 0/1 * * * ?
  first-sync-time:
    car-park-record: 2018-08-01 00:00:00
    passenger-flow-record: 2019-02-19 00:00:00
#log
logging:
  config: classpath:log4j2.xml

##服务注册到eureka地址
#eureka连接信息
eureka:
  instance:
    hostname: 127.0.0.1
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8100/eureka/



