spring:
  application:
    #网关服务名称
    name: tdp-basic-zuul-server
server:
  port: 80
#eureka连接信息
eureka:
  instance:
    hostname: 127.0.0.1
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8100/eureka/
#zuul配置
zuul:
  routes:
    #api文档
    tdp-api-server:
      path: /**
      serviceId: tdp-api-server
#设置ribbon的请求超时的时间
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
hystrix:
 command:
   default:
    execution:
      timeout:
        enabled: false
    isolation:
      thread:
        timeoutInMilliseconds: 50000






