#服务端口
server:
  port: 8080
spring:
  application:
    name: tdp-api-server
  redis:
    #数据库索引
    database: 10
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        #最大连接数
        max-active: 8
        #最大阻塞等待时间(负数表示没限制)
        max-wait: -1
        #最大空闲
        max-idle: 8
        #最小空闲
        min-idle: 0
    #连接超时时间
    timeout: 10000
#log
logging:
  config: classpath:log4j2.xml
#swagger
swagger:
  base-package: com.drore.tdp.api
  title: tdp对外接口文档
  description: tdp对外接口文档
  version: v1.0
  terms-of-service-url: 127.0.0.1:8080/swagger-ui.html
  contact:
    url:
    name: zengling
    email: 17363645521@163.com
##服务注册到eureka地址
#eureka连接信息
eureka:
  instance:
    hostname: 127.0.0.1
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8100/eureka/
#feign配置参数
tdp:
  feign:
    camera: tdp-hk-8700-server
